ex3:
	gcc -std=c99 -Wall -Wextra node.c ex3.c functions.c function_pointers.c -o ex3
fptest:
	gcc -std=c99 -Wall -Wextra node.c ex3.c functions.c function_pointers.c -o fptest

clean:
	rm -f *.o ex3 fptest
