all:
	gcc -std=c99 -Wall -Wextra node.c ex2.c -o ex2

rotatetest:
	gcc -std=c99 -Wall -Wextra node.c rotate.c -o rotatetest

reversetest:
	gcc -std=c99 -Wall -Wextra node.c reverse.c -o reversetest

clean:
	rm *.o ex2
